name: nyc311
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib~=3.3.4
  - notebook~=6.2.0
  - pandas~=1.2.3
  - pip=21.0.1
  - python=3.9.2
  - seaborn~=0.11.1
  - scikit-learn~=0.24.1
  - sqlalchemy==1.3.23
  - pip:
    - uszipcode==0.2.4
    - pyod==0.8.7
